#!/bin/bash

g++ -std=c++14 -O3 -larmadillo \
    -pedantic \
    -W \
    -Wall \
    -Wextra \
    -Wno-unused-local-typedefs \
    -Wwrite-strings \
    -Wundef \
    -Wno-missing-field-initializers \
    -Wpointer-arith \
    -Wcast-align \
    -Wno-unreachable-code \
    -Wnon-virtual-dtor \
    -Woverloaded-virtual \
    -lboost_program_options \
    $1 -o /tmp/x.x && /tmp/x.x "${@:2}"